import { useState } from "react";
import { useNavigate, useSearchParams } from "react-router-dom";
import { login, saveSession } from "../../lib/api/authApi";

export default function LoginPage() {
  const navigate = useNavigate(); const [searchParams] = useSearchParams(); const sessionExpired = searchParams.get("sessionExpired") === "1"; const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [showPassword, setShowPassword] = useState(false); const [loading, setLoading] = useState(false); const [error, setError] = useState("");
  async function handleSubmit(event) { event.preventDefault(); setLoading(true); setError(""); try { const session = await login(email, password); saveSession(session); navigate(session.user.role === "ORGANIZER" ? "/organizer" : session.user.role === "GATE" ? "/gate" : "/events"); } catch (requestError) { setError(requestError.response?.data?.error || "Não foi possível entrar. Tente novamente."); } finally { setLoading(false); } }
  return <div className="min-h-screen bg-slate-50"><div className="flex min-h-screen"><section className="hidden w-1/2 bg-slate-950 p-16 text-white lg:block"><button onClick={() => navigate("/events")} className="text-xl font-bold">elite<span className="text-rose-500">tix</span></button><div className="mt-48 max-w-md"><p className="font-bold text-rose-400">PLATAFORMA DE EVENTOS</p><h1 className="mt-4 text-5xl font-bold">Seu próximo evento começa aqui.</h1><p className="mt-5 text-slate-400">Acesse sua conta para comprar ingressos, gerenciar eventos ou validar entradas.</p></div></section><main className="flex flex-1 items-center justify-center p-6"><div className="w-full max-w-md"><button onClick={() => navigate("/events")} className="text-xl font-bold text-slate-900 lg:hidden">elite<span className="text-rose-500">tix</span></button><h2 className="mt-10 text-2xl font-bold">Entrar</h2><p className="mt-2 text-sm text-slate-500">Acesse sua conta para continuar.</p><form onSubmit={handleSubmit} className="mt-8 space-y-5">{sessionExpired && !error && <p className="rounded-md bg-amber-50 p-3 text-sm text-amber-700">Sua sessão expirou. Faça login novamente para continuar.</p>}{error && <p className="rounded-md bg-red-50 p-3 text-sm text-red-700">{error}</p>}<label className="block text-sm font-medium">E-mail<input type="email" value={email} onChange={(event) => setEmail(event.target.value)} required className="mt-2 w-full rounded-md border p-3" /></label><label className="block text-sm font-medium">Senha<div className="relative"><input type={showPassword ? "text" : "password"} value={password} onChange={(event) => setPassword(event.target.value)} required className="mt-2 w-full rounded-md border p-3 pr-20" /><button type="button" onClick={() => setShowPassword((value) => !value)} className="absolute right-3 top-5 text-xs">{showPassword ? "Ocultar" : "Mostrar"}</button></div></label><button disabled={loading} className="w-full rounded-md bg-slate-900 p-3 font-semibold text-white disabled:opacity-60">{loading ? "Entrando…" : "Entrar"}</button></form><p className="mt-8 border-t pt-5 text-center text-xs text-slate-400">Não existe cadastro. O acesso é fornecido pelo sistema.</p></div></main></div></div>;
}
