import { useEffect, useRef, useState } from "react";
import { useLocation, useNavigate } from "react-router-dom";
import { checkoutReservation } from "../../lib/api/checkoutApi";
import { createReservation } from "../../lib/api/reservationsApi";

const money = (value) => new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" }).format(value);
export default function CheckoutPage() {
  const navigate = useNavigate(); const { state } = useLocation(); const event = state?.event; const quantity = state?.quantity; const [reservation, setReservation] = useState(null); const [stateName, setStateName] = useState("loading"); const [error, setError] = useState(""); const created = useRef(false);
  useEffect(() => { if (!event || !quantity || created.current) return; created.current = true; (async () => { try { setReservation(await createReservation({ eventId: event.id, quantity })); setStateName("form"); } catch (requestError) { setError(requestError.response?.data?.error || "Não foi possível criar sua reserva."); setStateName("error"); } })(); }, [event, quantity]);
  async function pay(eventSubmit) { eventSubmit.preventDefault(); setStateName("loading"); setError(""); try { const result = await checkoutReservation(reservation.id); if (result.status === "approved") setStateName("approved"); else { setError(result.message || "Pagamento recusado."); setStateName("declined"); } } catch (requestError) { setError(requestError.response?.data?.error || "Não foi possível processar o pagamento."); setStateName("declined"); } }
  if (!event || !quantity) return <main className="min-h-screen p-8 text-center"><p>Não encontramos um pedido para checkout.</p><button onClick={() => navigate("/events")} className="mt-5 text-rose-600">Ver eventos</button></main>;
  const total = reservation?.total ?? state.total ?? event.price * quantity;
  return <div className="min-h-screen bg-slate-50"><main className="mx-auto max-w-5xl px-5 py-8"><button onClick={() => navigate(`/events/${event.id}`)} className="text-sm text-slate-500">← Voltar ao evento</button><div className="mt-6 grid gap-7 lg:grid-cols-[1fr_360px]"><section className="rounded-lg border bg-white p-7"><p className="font-mono text-xs font-bold text-rose-500">01 / PAGAMENTO</p><h1 className="mt-2 text-3xl font-black">Finalize sua compra</h1>{stateName === "form" && <form onSubmit={pay} className="mt-6 space-y-5"><Field label="Número do cartão" placeholder="0000 0000 0000 0000" /><div className="grid grid-cols-2 gap-4"><Field label="Validade" placeholder="MM / AA" /><Field label="CVV" placeholder="123" /></div><Field label="Nome no cartão" placeholder="Como impresso no cartão" /><button className="w-full rounded-md bg-rose-500 p-3 font-bold text-white">Pagar {money(total)}</button></form>}{stateName === "loading" && <State title="Preparando seu pedido" text="Aguarde enquanto confirmamos sua reserva." />}{stateName === "approved" && <State title="Pagamento aprovado!" text="Seus ingressos já estão disponíveis." button="Ver meus ingressos" onClick={() => navigate("/tickets")} />}{(stateName === "declined" || stateName === "error") && <State title={stateName === "declined" ? "Pagamento não aprovado" : "Não foi possível reservar"} text={error} button="Voltar aos eventos" onClick={() => navigate("/events")} error />}</section><aside className="h-fit rounded-lg border bg-white p-6"><p className="font-mono text-xs font-bold text-amber-500">SEU PEDIDO</p><h2 className="mt-3 text-lg font-black">{event.title}</h2><p className="mt-3 text-sm text-slate-500">{event.location}</p><p className="mt-1 text-xs text-slate-500">{new Date(event.eventDate).toLocaleString("pt-BR")}</p><div className="mt-5 border-y border-dashed py-4">{quantity} ingresso(s): {money(total)}</div><p className="mt-4 flex justify-between text-lg font-black"><span>Total</span><span className="text-rose-500">{money(total)}</span></p></aside></div></main></div>;
}
function Field({ label, placeholder }) { return <label className="block text-sm font-bold">{label}<input required placeholder={placeholder} className="mt-2 w-full rounded-md border p-3" /></label>; }
function State({ title, text, button, onClick, error }) { return <div className="py-14 text-center"><h2 className={error ? "text-2xl font-black text-red-600" : "text-2xl font-black"}>{title}</h2><p className="mt-2 text-sm text-slate-500">{text}</p>{button && <button onClick={onClick} className="mt-6 rounded-md bg-slate-950 px-5 py-3 text-sm font-bold text-white">{button}</button>}</div>; }
