import { useEffect, useMemo, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { getEventById } from "../../lib/api/eventsApi";

const money = (value) => new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" }).format(value);
export default function EventDetailPage() {
  const navigate = useNavigate(); const { id } = useParams(); const [event, setEvent] = useState(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [quantity, setQuantity] = useState(1);
  useEffect(() => { let active = true; (async () => { try { const value = await getEventById(id); if (active) setEvent(value); } catch (requestError) { if (active) setError(requestError.response?.data?.error || "Não foi possível carregar o evento."); } finally { if (active) setLoading(false); } })(); return () => { active = false; }; }, [id]);
  const availableTickets = Math.max(0, Number(event?.availableTickets ?? 0)); const total = useMemo(() => Number(event?.price || 0) * quantity, [event, quantity]);
  if (loading) return <PageMessage text="Carregando evento…" />; if (error || !event) return <PageMessage text={error || "Evento não encontrado."} error />;
  return <div className="min-h-screen bg-slate-50"><main className="mx-auto max-w-6xl px-6 py-8"><button onClick={() => navigate("/events")} className="mb-6 text-sm text-slate-600">← Voltar para eventos</button><div className="grid gap-8 lg:grid-cols-[1fr_360px]"><section className="overflow-hidden rounded-lg border border-slate-200 bg-white">{event.imageUrl && <img src={event.imageUrl} alt="" className="h-64 w-full object-cover" />}<div className="p-6"><p className="text-sm font-bold text-rose-500">{event.category}</p><h1 className="mt-2 text-3xl font-black">{event.title}</h1><p className="mt-5 text-sm text-slate-600">{new Date(event.eventDate).toLocaleString("pt-BR")}</p><p className="mt-2 text-sm text-slate-600">{event.location}</p><h2 className="mt-8 text-lg font-bold">Sobre o evento</h2><p className="mt-3 text-sm leading-6 text-slate-600">{event.description}</p></div></section><aside className="h-fit rounded-lg border border-slate-200 bg-white p-6"><h2 className="text-lg font-bold">Comprar ingressos</h2><div className="mt-5 space-y-3 border-b border-slate-200 pb-5"><p className="flex justify-between text-sm"><span>Valor do ingresso</span><b>{money(event.price)}</b></p><p className="flex justify-between text-sm"><span>Disponíveis</span><b>{availableTickets}</b></p></div>{availableTickets === 0 ? <p className="mt-6 text-red-600">Este evento está esgotado.</p> : <><div className="mt-6 flex items-center justify-between rounded-md border"><button onClick={() => setQuantity((value) => Math.max(1, value - 1))} className="h-11 w-12">−</button><b>{quantity}</b><button onClick={() => setQuantity((value) => Math.min(availableTickets, value + 1))} className="h-11 w-12">+</button></div><p className="mt-6 flex justify-between"><span>Total</span><b>{money(total)}</b></p><button onClick={() => navigate("/checkout", { state: { event, quantity, total } })} className="mt-5 w-full rounded-md bg-rose-500 px-5 py-3 font-bold text-white">Continuar</button></>}</aside></div></main></div>;
}
function PageMessage({ text, error }) { const navigate = useNavigate(); return <main className="min-h-screen bg-slate-50 p-8 text-center"><p className={error ? "text-red-600" : ""}>{text}</p><button onClick={() => navigate("/events")} className="mt-5 text-rose-600">Voltar para eventos</button></main>; }
